config/routes.rb
Rails.application.routes.draw do
  resources :washes, only: :index
  resources :trucks, only: [:new, :index, :create]
  resources :cars, only: [:new, :index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  include Vehicle

  has_one :wash, as: :washable, dependent: :destroy

  def price
    5
  end
end

app/models/car_wash.rb
class CarWash < SimpleDelegator
  def wash
    @wash ||= Wash.create(price: price, washable: vehicle)
  end

  def price
    vehicle.price * discount
  end

  private

  def vehicle
    __getobj__
  end

  def discount
    times_washed == 2 ? 0.5 : 1
  end

  def times_washed
    vehicle.class.where(license_plate: vehicle.license_plate).count
  end
end

app/models/concerns/vehicle.rb
module Vehicle
  extend ActiveSupport::Concern

  STOLEN_PLATES = ["1111111"]

  included do
    validates_presence_of :license_plate
    validates :license_plate, exclusion: { in: STOLEN_PLATES, message: "This vehicle is stolen, please report to the authorities" }
  end
end

app/models/truck.rb
class Truck < ApplicationRecord
  include Vehicle

  has_one :wash, as: :washable, dependent: :destroy

  validates :tailgate_up, acceptance: { message: 'Tailgates must be up, please ask the customer to raise their tailgate.' }


  def price
    10 + muddy_price
  end

  private

  def muddy_price
    muddy? ? 2 : 0
  end
end

app/models/wash.rb
class Wash < ApplicationRecord
  belongs_to :washable, polymorphic: true

  delegate :license_plate, to: :washable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

   # GET /cars/new
  def new
    @car = Car.new
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.create(car_params)

    respond_to do |format|
      if @car.save
        CarWash.new(@car).wash
        format.html { redirect_to washes_path, notice: 'Car was successfully washed.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def car_params
      params.require(:car).permit(:license_plate)
    end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController

  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.all
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        CarWash.new(@truck).wash
        format.html { redirect_to washes_path, notice: 'Truck was successfully washed.' }
      else
        format.html { render :new }
      end
    end
  end

  private

    def truck_params
      params.require(:truck).permit(:license_plate, :tailgate_up, :muddy)
    end
end

app/controllers/washes_controller.rb
class WashesController < ApplicationController
  def index
    @washes = Wash.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :license_plate %>
    <%= form.text_field :license_plate, id: :car_license_plate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>License plate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.license_plate %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', washes_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>License plate:</strong>
  <%= @car.license_plate %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Washr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trucks/_form.html.erb
<%= form_with(model: truck, local: true) do |form| %>
  <% if truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :license_plate %>
    <%= form.text_field :license_plate, id: :truck_license_plate %>
  </div>

  <div class="field">
    <%= form.label :tailgate_up %>
    <%= form.check_box :tailgate_up, id: :truck_tailgate_up %>
  </div>

  <div class="field">
    <%= form.label :muddy %>
    <%= form.check_box :muddy, id: :truck_muddy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trucks</h1>

<table>
  <thead>
    <tr>
      <th>License plate</th>
      <th>Tailgate Up?</th>
      <th>Muddy?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.license_plate %></td>
        <td><%= truck.tailgate_up %></td>
        <td><%= truck.muddy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truck', new_truck_path %>

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Back', washes_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>License plate:</strong>
  <%= @truck.license_plate %>
</p>

<p>
  <strong>Tailgate up:</strong>
  <%= @truck.tailgate_up %>
</p>

<p>
  <strong>Muddy:</strong>
  <%= @truck.muddy %>
</p>

<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>

app/views/washes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Washes</h1>

<%= link_to 'New Car', new_car_path %>
<%= link_to 'New Truck', new_truck_path %>

<table>
  <thead>
    <tr>
      <th>Vehicle Type</th>
      <th>License Plate</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @washes.each do |wash| %>
      <tr>
        <td><%= wash.washable_type %></td>
        <td><%= wash.license_plate %></td>
        <td><%= wash.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>